# Oznacza jako "zastałe" PR oraz issue w których nie odnotowano aktywnosci przez okreslony czas
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "59 23 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.stalerToken }}
        stale-issue-message: 'This issue is stalled'
        stale-pr-message: 'This PR is stalled'
        stale-issue-label: 'no-activity'
        stale-pr-label: 'no-activity'
